<a href="https://colab.research.google.com/github/pratik-0013/pratik-0013/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn

# DataTypes & Attributes


In [ ]:
# NumPy's main data type is ndarry
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [ ]:
type(a1)

numpy.ndarray

In [ ]:
a2 = np.array([[1, 2.0, 3.3],
             [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
a1.shape

(3,)

In [ ]:
a2.shape

(2, 3)

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a1.ndim, a2.ndim, a3.ndim # no of dimensions

(1, 2, 3)

In [ ]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [ ]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [ ]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [ ]:
# Create a dataframe from a numpy array
df2 = pd.DataFrame(a2)
df

NameError: name 'df' is not defined

## 2. Create NumPy Array

In [ ]:
sample_array = np.array([1, 2, 3])
sample_array

In [ ]:
sample_array.dtype

In [ ]:
ones = np.ones((5, 6))
ones

In [ ]:
ones.dtype

In [ ]:
type(ones)

In [ ]:
zeros = np.zeros((2, 3))
zeros

In [ ]:
zeros.dtype

In [ ]:
type(zeros)

In [ ]:
range_array = np.arange(0, 12, 2)
range_array

In [ ]:
range_array.dtype

In [ ]:
type(range_array)

In [ ]:
random_array = np.random.randint(0, 99, size = (5, 5))
random_array

In [ ]:
random_array.size

In [ ]:
random_array.shape

In [ ]:
rand_array2 = np.random.random((4,2))
rand_array2

In [ ]:
rand_array2.shape

In [ ]:
rand_array2.size

In [ ]:
rand_array3 = np.random.rand(5,3) # When NumPy genrates random numbers they're actually psudo random numbers
rand_array3

In [ ]:
# When NumPy genrates random numbers they're actually psudo random numbers
# Psudo-random numbers
np.random.seed(99999) # to get same random no always
rand4 = np.random.randint(10, size=(5, 3))
rand4

In [ ]:
 rand4.shape

## 3. Different ways to Viewing arrays and matrices

In [ ]:
np.unique(rand4)

In [ ]:
a1

In [ ]:
a2

In [ ]:
a3

In [ ]:
a3[1]

In [ ]:
a2[1]

In [ ]:
a3[:2, :2, :2]

In [ ]:
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

In [ ]:
a4.shape

In [ ]:
a4.ndim

In [ ]:
a4[:, :, :, :1]

## 4. Manipulating & comparing arrays

### Arithmatic

In [ ]:
a1

In [ ]:
ones = np.ones(3)
ones

In [ ]:
a1 + ones

In [ ]:
a1 - ones

In [ ]:
a1 * ones

In [ ]:
a2

In [ ]:
a1 * a2

In [ ]:
a2

In [ ]:
a3

In [ ]:
# a2 * a3 error 

In [ ]:
a2**2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = preforming the same opration on a number of things

In [ ]:
l = [1, 2, 3]
type(l)

In [ ]:
sum(l)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
np.sum(a1)

In [ ]:
sum(a1)

## Use Python's methond (sum()) on Python datatypes and 

## use NumPy's Method (np.sum()) on NumPy arrays

In [ ]:
# Create a massive NumPy array
mass_array = np.random.random(100000)
mass_array.size

In [ ]:
mass_array[:10]

In [ ]:
%timeit sum(mass_array) # py sum()
%timeit np.sum(mass_array) # np sum()

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
plt.hist(high_var_array)
plt.show()

## Reshaping & transposing 

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a2.shape

(2, 3)

In [ ]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [ ]:
# a2 * a3    error 

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
# Reshape
a2.reshape(2, 3, 1)

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)
a2_reshape

array([[[1. ],
        [2. ],
        [3.3]],

       [[4. ],
        [5. ],
        [6.5]]])

In [ ]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [ ]:
# Transpose
a2.T

array([[1. , 4. ],
       [2. , 5. ],
       [3.3, 6.5]])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a3.shape

(2, 3, 3)

In [ ]:
a3.T

array([[[ 1, 10],
        [ 4, 13],
        [ 7, 16]],

       [[ 2, 11],
        [ 5, 14],
        [ 8, 17]],

       [[ 3, 12],
        [ 6, 15],
        [ 9, 18]]])

In [ ]:
a3.T.shape

(3, 3, 2)

## Dot product


In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3))
mat2 = np.random.randint(10, size = (5,3))

mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [ ]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [ ]:
# Element-Wise multiplication (Hadamard product)
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [ ]:
mat1.shape, mat2.T.shape

((5, 3), (3, 5))

In [ ]:
transpose_mat2 = mat2.T
transpose_mat2

array([[6, 8, 9, 4, 3],
       [7, 1, 8, 3, 5],
       [7, 5, 9, 0, 0]])

In [ ]:
mat3 = np.dot(mat1,transpose_mat2)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [ ]:
mat3.shape

(5, 5)

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [ ]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=["Almond butter", "Peanut butter", "Cashew butter"])
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [ ]:
prices.shape

(3,)

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [ ]:
prices.shape

(3,)

In [ ]:
sales_amounts.shape

(5, 3)

In [ ]:
# total_sales = prices.dot(sales_amounts) error

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

array([240, 138, 458, 232, 142])

In [ ]:
# Create daily_sales
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [ ]:
weekly_sales.T.shape

(3, 5)

In [ ]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales.shape

(1, 5)

In [ ]:
weekly_sales.shape

(5, 3)

### Comparison Operators

In [ ]:
a1

array([1, 2, 3])

In [ ]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [ ]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [ ]:
bool_array = a1 >= a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [ ]:
a1 > 5

array([False, False, False])

In [ ]:
a1 == a1 

array([ True,  True,  True])

### 5. Sorting arrays

In [ ]:
random_array = np.random.randint(10, size=(3, 5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
random_array.shape

(3, 5)

In [ ]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [ ]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]], dtype=int64)

In [ ]:
a1

array([1, 2, 3])

In [ ]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [ ]:
np.argmin(a1)

0

In [ ]:
np.argmax(a1)

2

In [ ]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [ ]:
np.argmax(random_array, axis=1)

array([4, 1, 1], dtype=int64)

## 6. Practical Example - NumPy in Action!!!!